
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fndygxqzizadrjexxmcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZHlneHF6aXphZHJqZXh4bWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDA0NDQsImV4cCI6MjA2MjM3NjQ0NH0.9ROBZC79m3LSODIjeEYCGfzzcYzVlgpYmyoWQsOzbvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'tower-management-auth',
  },
});
